import type { Metadata } from 'next';
import './globals.css';
import Modal from '@/components/Modal';

export const metadata: Metadata = {
  title: 'Trello 2.0 AI Clone',
  description: 'Generated by MDBT',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Modal />
      </body>
    </html>
  );
}
